name       : haskell-xml
version    : 1.3.14
release    : 3
source     :
    - https://hackage.haskell.org/package/xml-1.3.14/xml-1.3.14.tar.gz : 32d1a1a9f21a59176d84697f96ae3a13a0198420e3e4f1c48abbab7d2425013d
license    : BSD-3-Clause
component  : programming.haskell
summary    : A simple XML library.
description: |
    A simple XML library.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
